import './scss/main.scss';
import './js/main';
import './js/skycons';
import './js/mapInit';
import './js/nameOfCurrentLocationInit';
import './js/backgroundInit';
import './js/hoursAndMinutesInit';
import './js/animatedIcons';
import './js/errorRequestInit';
